name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ffzakarias/myrepo:my-static-website-image 

    - name: Run Docker container
      run: |
        docker run -d --name my-static-website -p 8080:80 my-static-website-image
        sleep 5

    - name: Test website
      run: |
        curl http://localhost:8080 | grep '<title>My Static Website</title>'
    - name: Stop and remove Docker container
      run: docker rm -f my-static-website
